
name: automerge
on:
  schedule:
    - cron: '59 7 * * *'


jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: setTimezone
        uses: "szenius/set-timezone@v1.0"
        with:
          timezoneLinux: "Canada/Pacific"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
